Option Explicit

Public Sub Dimenzioniraj()
    Dim line As AcadDimAligned
    Dim p0(0 To 2) As Double
    Dim p1(0 To 2) As Double
    Dim p2(0 To 2) As Double
    Dim broj(0 To 2) As Double
    p1(0) = 0: p1(1) = 0: p1(2) = 0
    p2(0) = 0: p2(1) = 100: p2(2) = 0
    broj(0) = 35: broj(1) = 0: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -10: p1(1) = 0: p1(2) = 0
    p2(0) = -10: p2(1) = 50: p2(2) = 0
    broj(0) = 15: broj(1) = 0: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = 0: p1(1) = 100: p1(2) = 0
    p2(0) = -200: p2(1) = 100: p2(2) = 0
    broj(0) = 0: broj(1) = 115: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -200: p1(1) = 100: p1(2) = 0
    p2(0) = -286.6: p2(1) = 50: p2(2) = 0
    broj(0) = -295: broj(1) = 60: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -286.6: p1(1) = 0: p1(2) = 0
    p2(0) = -286.6: p2(1) = 50: p2(2) = 0
    broj(0) = -300: broj(1) = 0: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -205: p1(1) = 35: p1(2) = 0
    p2(0) = -130: p2(1) = 35: p2(2) = 0
    broj(0) = 0: broj(1) = -15: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -130: p1(1) = 30: p1(2) = 0
    p2(0) = -65: p2(1) = 30: p2(2) = 0
    broj(0) = 0: broj(1) = -15: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -65: p1(1) = 30: p1(2) = 0
    p2(0) = -30: p2(1) = 30: p2(2) = 0
    broj(0) = 0: broj(1) = -15: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    p1(0) = -30: p1(1) = 30: p1(2) = 0
    p2(0) = 0: p2(1) = 30: p2(2) = 0
    broj(0) = 0: broj(1) = -15: broj(2) = 0
    Set line = ThisDrawing.ModelSpace.AddDimAligned(p1, p2, broj)
    Dim ugao As AcadDimAngular
    p0(0) = -200: p0(1) = 100: p0(2) = 0
    p1(0) = -180: p1(1) = 100: p1(2) = 0
    p2(0) = -234: p2(1) = 80: p2(2) = 0
    broj(0) = -215: broj(1) = 85: broj(2) = 0
    Set ugao = ThisDrawing.ModelSpace.AddDimAngular(p0, p1, p2, broj)
    Dim manjiKrug As AcadDimRadial
    p1(0) = -205: p1(1) = 50: p1(2) = 0
    p2(0) = -225: p2(1) = 50: p2(2) = 0
    Set manjiKrug = ThisDrawing.ModelSpace.AddDimRadial(p1, p2, 0)
    Dim veciKrug As AcadDimDiametric
    p1(0) = -165: p1(1) = 50: p1(2) = 0
    p2(0) = -95: p2(1) = 50: p2(2) = 0
    Set veciKrug = ThisDrawing.ModelSpace.AddDimDiametric(p1, p2, 0)
End Sub